FROM ubuntu:22.04
RUN apt update
RUN apt install -y python3 python3-pip
RUN pip install -U og_proto og_sdk og_agent og_kernel hapless
RUN adduser octogen
ADD server /bin/
ADD start_all.sh /bin/
ADD add_endpoint.sh /bin/
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update
RUN apt --fix-broken install
RUN apt-get install google-chrome-stable -y
