name: Python Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          WS_DIR=`pwd`
          bash start_sandbox.sh
          cd ${WS_DIR}/sdk
          pytest tests/*.py
          cd ${WS_DIR}/kernel
          pytest tests/*.py
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: log-artifact
          path: |
            sandbox/agent/*.log
            sandbox/kernel/*.log
