# .github/workflows/ci-cd.yml
on: workflow_dispatch
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: build packages
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          VERSION=${TAG#*v}
          bash build_package.sh ${VERSION}

      - name: Publish Proto
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: proto/dist

      - name: Publish Kernel
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: kernel/dist

      - name: Publish Agent
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: agent/dist
      - name: Publish Chat
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: chat/dist
